[profile.default]
default_chain = "base"
evm_version = "cancun"
libs = ["lib"]
out = "out"
solc_version = "0.8.28"
src = "src"
via_ir = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[rpc_endpoints]
base = "${BASE_RPC_URL}"

[etherscan]
base = { key = "${BASE_ETHERSCAN_API_KEY}" }
